dist: trusty

language: node_js

node_js:
  - "9.3.0"

install:
  - npm install -g truffle codecov
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint:js
  - npm run lint:sol
  - npm run test:cov
  - codecov

# notifications:
#   slack: to be filled in
