dist: trusty
language: node_js
node_js:
- 9.3.0
install:
- npm install -g truffle codecov
- npm install
cache:
  directories:
  - node_modules
script:
- npm run lint:js
- npm run lint:sol
- npm run test:cov
- codecov
notifications:
  slack:
    rooms:
      secure: awo8oLXz7zLSl420DrcYP6uOLh3ORZ5TRa7564iQIeAD9KgC8vaH8bdQ1GbrdqHpiTnciV5Z7x/MmOr/Qk5BUTXotaHQuZXcOUgp3F7K7p639fYpTSSeZUHMz2Sk5Crox0ZL2cj7BaByXN4qSMtIzjhbGnTb0QmnQSMvWog71kZew/mDtDKJr5mZlOcx0iUuH3u4477sl78TENzj0qaOeaKI34Ug1R78c51SYgu6vf6yeqgg5g8Qxrnm9LhHoejR3mcslRSLxkbV/qiPvpjOCC+tWR2093iRS4uFE9IDlfejD/AD2FHds3LcxBfrztjJ5Iy7ZOhwa2pi3ef/Ej8LtNXQz9oM9EY7+E1tMVCdhz4IQcpZEVTDw9UAROvX1OPHC0Uv6Eq8Kx5uLAxg5U0auIpRrYX+1l1CTmSj8nRifCFyJtGa3RIrFUno+gOxmUqNd91+Q9BhikVGPc550/zxbQNIxIvr4RB30IuMhFfWOHBlG0Comeiu+DB1Nfw6mRLeFemWnEKaIDfr3ONnWinPQnWDaFelW728KoZjsgAzoteDtoZoI2eBvzA4y/8Zs8kJEkcF/9J46Ai/Qo3u4SqkrAcCSMUqpZgJjdEX+uLd40stIC760NW8OdNw3grMtWWavq7S68VAdNpFzA6GkJeIh3Mte2g0Ak0bAlmo6rtPkLM=
