dist: trusty

language: node_js

node_js:
  - "9.3.0"

install:
  - npm install -g truffle codecov
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint:js
  - npm run lint:sol
  - npm run test:cov
  - codecov

notifications:
  slack:
    secure: AfTRdnMb2y0wMnRvBk6KxPQaKO0EtN9bmEau186hEgsM9js1P3XM+xenh24xKazShSLGy/5uLvluhRJBZgXOZhgDUySWH6OiLWQx8vg/skz7ZyAMcmX1pvBFs2zrNOBs3g3FAMaKef4CeLR7jgwBoTtfhBUoPLLTPnnAax8LNoM4A/E5el9GdxkHVOOuB2MH5yBO4m/h86QIpIbgf/0piWoZZks3I2pufyFZNG4MIh7/sLDA+LqvsNEpB9lUZFkrwfbm0+9uyG9OcWCmGqH5k0gSper38/NaoE+xvaP1hVnJYa2IqPM90K+uZvY5yUn2WXT4O6Q1YaxHdSLkOJzWDi5opOWydWiR6+mADAfNikdfRQnnQYVALlzZ1hEqGZ54na4ovtdle23epJrSqlYO+cFsJ94RY4+BzOnnio2YpIr8XJurJ8fke/3XKXQ9d15HFLnOOIm/ZZwH/QeYG2JGy/Erw3VQVbjwFMkooRTAhGJF+U3tVB5WXyrQaw2iTOQa/vcxq1zhTyw8xvPqcgSsZ2rzihKRK8D01S1+7miCcjsN6E1PRm5J0r3jmUiV28Vr+74zRrXD2GNLU9q00wklX5h238oXLu7vVW8Ir4WqS5kvmSL1cG69W8VC6FZ0Wvn0oHG7kiQXcY+5ULGI4zrbyskv/1SURMCR324MDTEavS8=
